id: A5E17FC7D
base_file: f3B15.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:29:36.607296
  last_modified_at: 2022-06-17 14:29:36.607306
