id: A5E17FC7D
base_file: fB98B.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:29:36.644503
  last_modified_at: 2022-06-17 14:29:36.644508
