id: A5E17FC7D
base_file: fEBE6.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:29:36.662668
  last_modified_at: 2022-06-17 14:29:36.662679
