id: A5E17FC7D
base_file: fABBF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:29:36.631884
  last_modified_at: 2022-06-17 14:29:36.631890
